### ISSUE TITLE
Link source from that information to timer

### ISSUE THREAD

**Issue by axi92** [CactusPuppy/ow2countdown#17]
Can you add the link to the source where you get the information on when what ends/starts?
Most people ask if its valid or where the info came from.

**Comment by CactusPuppy** [comment]
Working on this right now! It'll be on a details page for each event and will look something like this (styling is WIP):
![image](https://user-images.githubusercontent.com/10406383/196554558-dd076518-d380-4007-909b-0c2c7039500e.png)
