### ISSUE TITLE
[FR] Idea for streamers: embed the countdown

### ISSUE THREAD

**Issue by axi92** [CactusPuppy/ow2countdown#56]
Just an Idea for streamers that want to countdown new events. To embed the countdown only.
something like:
https://ow2countdown.com/event/87/talantis&countdownonly=true
To only get this on the page:
![image](https://user-images.githubusercontent.com/1394837/233978136-ea638066-105f-4be6-83a5-9e115f86e66d.png)

I dont know if it is the usecase of ow2countdown.

**Comment by CactusPuppy** [comment]
Oooh good idea, I'll probably make this a separate path for my own sanity but it's a great idea.

**Comment by CactusPuppy** [comment]
Note to self: in the future, add some interactive method for non-power-users to customize the embed page
